// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Qm96J61bB9Ecl8N3nEzxtSfywZZKuFs',
    appId: '1:1092256127457:web:83c80cdd48a09873ab1aa0',
    messagingSenderId: '1092256127457',
    projectId: 'project1-c7e6a',
    authDomain: 'project1-c7e6a.firebaseapp.com',
    storageBucket: 'project1-c7e6a.appspot.com',
    measurementId: 'G-9B2BWDTYLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu6XdogdP_GGxB79e_08s1XtGcEknQu4g',
    appId: '1:1092256127457:android:af10028d733e7f3bab1aa0',
    messagingSenderId: '1092256127457',
    projectId: 'project1-c7e6a',
    storageBucket: 'project1-c7e6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_mgRRh5N6sVj2DO_sXOHt4qoPDnfVqRM',
    appId: '1:1092256127457:ios:cb7c0cd05d6511edab1aa0',
    messagingSenderId: '1092256127457',
    projectId: 'project1-c7e6a',
    storageBucket: 'project1-c7e6a.appspot.com',
    iosBundleId: 'com.example.newEventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_mgRRh5N6sVj2DO_sXOHt4qoPDnfVqRM',
    appId: '1:1092256127457:ios:cb7c0cd05d6511edab1aa0',
    messagingSenderId: '1092256127457',
    projectId: 'project1-c7e6a',
    storageBucket: 'project1-c7e6a.appspot.com',
    iosBundleId: 'com.example.newEventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6Qm96J61bB9Ecl8N3nEzxtSfywZZKuFs',
    appId: '1:1092256127457:web:3befa9da7b699c30ab1aa0',
    messagingSenderId: '1092256127457',
    projectId: 'project1-c7e6a',
    authDomain: 'project1-c7e6a.firebaseapp.com',
    storageBucket: 'project1-c7e6a.appspot.com',
    measurementId: 'G-HRSYZPD7NL',
  );
}
